spring:
  application:
    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
server:
  port: ${PORT:8000}
zuul.host.socket-timeout-millis: 20000
zuul.host.connect-timeout-millis: 20000
ribbon.ConnectTimeout: 10000
ribbon.ReadTimeout: 10000

# All services are added into Zuul routes automatically as default.
# You can disable it with the ignored-services property set to *
# See: https://cloud.spring.io/spring-cloud-netﬂix/multi/multi__router_and_ﬁlter_zuul.html
zuul:
  ignored-services: "*"
  routes:
    ui-service:
      path: "/ui/**" 
      service-id: frontend-service 
      strip-prefix: false
    project-service:
      path: "/api/project/**"
      service-id: project-service
      strip-prefix: true
      sensitiveHeaders: Cookie,Set-Cookie # Authentication
    compiler-service:
      path: "/api/compiler/**"
      service-id: compiler-service
      strip-prefix: true
    darkmode-service:
      path: "/dark-mode/**"
      service-id: darkmode-service
      strip-prefix: false

proxy:
  auth:
    routes:
      project-service: oauth2

security:
  oauth2:
    client:
      clientId: ${CLIENT-ID}
      clientSecret: ${CLIENT-SECRET}
      accessTokenUri: https://gitlab.lrz.de/oauth/token
      userAuthorizationUri: https://gitlab.lrz.de/oauth/authorize
      scope:
        - read_user
        - api
    resource:
      userInfoUri: https://gitlab.lrz.de/api/v4/user
